app:
  port: 8080
server:
  mode: release

db:
  host: localhost
  port: 5432
  user: postgres
  password: 153247
  dbname: blogdb
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "dGhpcyBpcyBhIHNlY3VyZSBqd3Qgc2VjcmV0IGtleSBmb3IgaHMyNTYK"
  expire_hours: 72

log:
  level: debug

